language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t slydudi/docker-simpleweb .
    
deploy:
    provider:   elasticbeanstalk
    region:     "us-east-2"
    app:        "docker-simpleweb"
    env:        "Dockersimpleweb-env-1"
    bucket_name: "elasticbeanstalk-us-east-2-309255062502"
    backet_path: "dockersimpleweb"
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secure_access_key: $AWS_SECRET_KEY
        
        
        
        