language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t slydudi/docker-simpleweb -f Dockerfile.dev .
    
deploy:
    provider:   elasticbeanstalk
    region:     "us-east-2"
    app:        "dockersimpleweb"
    env:        "dockersimpleweb-env"
    bucket_name: "elasticbeanstalk-us-east-2-309255062502"
    backet_path: "dockersimpleweb"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secure_access_key: 
        secure: "$AWS_ACCESS_KEY"
        
        
        
        